/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\cbu" *)
(* src = "cba.sv:36.1-110.10" *)
module \$paramod\cbu\BLOCK_WIDTH=s32'00000000000000000000000000100000 (a, b, c_in, sum, c_out);
  (* src = "cba.sv:39.35-39.36" *)
  wire _000_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _001_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _002_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _003_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _004_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _005_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _006_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _007_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _008_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _009_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _010_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _011_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _012_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _013_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _014_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _015_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _016_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _017_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _018_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _019_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _020_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _021_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _022_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _023_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _024_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _025_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _026_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _027_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _028_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _029_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _030_;
  (* src = "cba.sv:39.35-39.36" *)
  wire _031_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _032_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _033_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _034_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _035_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _036_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _037_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _038_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _039_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _040_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _041_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _042_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _043_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _044_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _045_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _046_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _047_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _048_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _049_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _050_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _051_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _052_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _053_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _054_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _055_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _056_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _057_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _058_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _059_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _060_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _061_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _062_;
  (* src = "cba.sv:40.35-40.36" *)
  wire _063_;
  (* src = "cba.sv:41.17-41.21" *)
  wire _064_;
  (* src = "cba.sv:43.18-43.23" *)
  wire _065_;
  (* src = "cba.sv:98.25-98.30" *)
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  (* src = "cba.sv:89.19-89.45" *)
  wire _113_;
  (* src = "cba.sv:89.19-89.55" *)
  wire _114_;
  (* src = "cba.sv:89.19-90.25" *)
  wire _115_;
  (* src = "cba.sv:89.19-90.35" *)
  wire _116_;
  (* src = "cba.sv:89.19-90.45" *)
  wire _117_;
  (* src = "cba.sv:89.19-90.55" *)
  wire _118_;
  (* src = "cba.sv:89.19-91.25" *)
  wire _119_;
  (* src = "cba.sv:89.19-91.35" *)
  wire _120_;
  (* src = "cba.sv:89.19-91.46" *)
  wire _121_;
  (* src = "cba.sv:89.19-91.56" *)
  wire _122_;
  (* src = "cba.sv:89.19-92.26" *)
  wire _123_;
  (* src = "cba.sv:89.19-92.36" *)
  wire _124_;
  (* src = "cba.sv:89.19-92.46" *)
  wire _125_;
  (* src = "cba.sv:89.19-92.56" *)
  wire _126_;
  (* src = "cba.sv:89.19-93.26" *)
  wire _127_;
  (* src = "cba.sv:89.19-93.36" *)
  wire _128_;
  (* src = "cba.sv:89.19-93.46" *)
  wire _129_;
  (* src = "cba.sv:89.19-93.56" *)
  wire _130_;
  (* src = "cba.sv:89.19-94.26" *)
  wire _131_;
  (* src = "cba.sv:89.19-94.36" *)
  wire _132_;
  (* src = "cba.sv:89.19-94.46" *)
  wire _133_;
  (* src = "cba.sv:89.19-94.56" *)
  wire _134_;
  (* src = "cba.sv:89.19-95.26" *)
  wire _135_;
  (* src = "cba.sv:89.19-95.36" *)
  wire _136_;
  (* src = "cba.sv:89.19-95.46" *)
  wire _137_;
  (* src = "cba.sv:89.19-95.56" *)
  wire _138_;
  (* src = "cba.sv:89.19-96.26" *)
  wire _139_;
  (* src = "cba.sv:89.19-96.36" *)
  wire _140_;
  (* src = "cba.sv:89.19-96.46" *)
  wire _141_;
  (* src = "cba.sv:89.19-89.35" *)
  wire _142_;
  (* src = "cba.sv:39.35-39.36" *)
  input [31:0] a;
  wire [31:0] a;
  (* src = "cba.sv:40.35-40.36" *)
  input [31:0] b;
  wire [31:0] b;
  (* src = "cba.sv:41.17-41.21" *)
  input c_in;
  wire c_in;
  (* src = "cba.sv:43.18-43.23" *)
  output c_out;
  wire c_out;
  (* src = "cba.sv:98.25-98.30" *)
  wire [32:0] carry;
  (* src = "cba.sv:46.9-46.15" *)
  wire prop_0;
  (* src = "cba.sv:46.17-46.23" *)
  wire prop_1;
  (* src = "cba.sv:48.22-48.29" *)
  wire prop_10;
  (* src = "cba.sv:48.31-48.38" *)
  wire prop_11;
  (* src = "cba.sv:49.6-49.13" *)
  wire prop_12;
  (* src = "cba.sv:49.15-49.22" *)
  wire prop_13;
  (* src = "cba.sv:49.24-49.31" *)
  wire prop_14;
  (* src = "cba.sv:49.33-49.40" *)
  wire prop_15;
  (* src = "cba.sv:50.6-50.13" *)
  wire prop_16;
  (* src = "cba.sv:50.15-50.22" *)
  wire prop_17;
  (* src = "cba.sv:50.24-50.31" *)
  wire prop_18;
  (* src = "cba.sv:50.33-50.40" *)
  wire prop_19;
  (* src = "cba.sv:46.25-46.31" *)
  wire prop_2;
  (* src = "cba.sv:51.6-51.13" *)
  wire prop_20;
  (* src = "cba.sv:51.15-51.22" *)
  wire prop_21;
  (* src = "cba.sv:51.24-51.31" *)
  wire prop_22;
  (* src = "cba.sv:51.33-51.40" *)
  wire prop_23;
  (* src = "cba.sv:52.6-52.13" *)
  wire prop_24;
  (* src = "cba.sv:52.15-52.22" *)
  wire prop_25;
  (* src = "cba.sv:52.24-52.31" *)
  wire prop_26;
  (* src = "cba.sv:52.33-52.40" *)
  wire prop_27;
  (* src = "cba.sv:53.6-53.13" *)
  wire prop_28;
  (* src = "cba.sv:53.15-53.22" *)
  wire prop_29;
  (* src = "cba.sv:46.33-46.39" *)
  wire prop_3;
  (* src = "cba.sv:53.24-53.31" *)
  wire prop_30;
  (* src = "cba.sv:53.33-53.40" *)
  wire prop_31;
  (* src = "cba.sv:47.6-47.12" *)
  wire prop_4;
  (* src = "cba.sv:47.14-47.20" *)
  wire prop_5;
  (* src = "cba.sv:47.22-47.28" *)
  wire prop_6;
  (* src = "cba.sv:47.30-47.36" *)
  wire prop_7;
  (* src = "cba.sv:48.6-48.12" *)
  wire prop_8;
  (* src = "cba.sv:48.14-48.20" *)
  wire prop_9;
  (* src = "cba.sv:54.6-54.14" *)
  wire prop_cbu;
  (* src = "cba.sv:42.36-42.39" *)
  output [31:0] sum;
  wire [31:0] sum;
  sky130_fd_sc_hd__xnor2_1 _143_ (
    .A(_028_),
    .B(_060_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__xnor2_1 _144_ (
    .A(_002_),
    .B(_034_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__xnor2_1 _145_ (
    .A(_013_),
    .B(_045_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _146_ (
    .A(_012_),
    .B(_044_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(_024_),
    .B(_056_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _148_ (
    .A1_N(_024_),
    .A2_N(_056_),
    .B1(_020_),
    .B2(_052_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a21oi_1 _149_ (
    .A1(_015_),
    .A2(_047_),
    .B1(_084_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__xnor2_1 _150_ (
    .A(_017_),
    .B(_049_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__xnor2_1 _151_ (
    .A(_022_),
    .B(_054_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__xnor2_1 _152_ (
    .A(_008_),
    .B(_040_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__xnor2_1 _153_ (
    .A(_023_),
    .B(_055_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xnor2_1 _154_ (
    .A(_000_),
    .B(_032_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _155_ (
    .A(_025_),
    .B(_057_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__xnor2_1 _156_ (
    .A(_004_),
    .B(_036_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__xnor2_1 _157_ (
    .A(_014_),
    .B(_046_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_1 _158_ (
    .A(_019_),
    .B(_051_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xnor2_1 _159_ (
    .A(_027_),
    .B(_059_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor2_1 _160_ (
    .A(_026_),
    .B(_058_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _161_ (
    .A(_006_),
    .B(_038_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _162_ (
    .A1_N(_006_),
    .A2_N(_038_),
    .B1(_003_),
    .B2(_035_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21oi_1 _163_ (
    .A1(_029_),
    .A2(_061_),
    .B1(_098_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__xnor2_1 _164_ (
    .A(_031_),
    .B(_063_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__xor2_1 _165_ (
    .A(_009_),
    .B(_041_),
    .X(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _166_ (
    .A(_011_),
    .B(_043_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__xnor2_1 _167_ (
    .A(_005_),
    .B(_037_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xor2_1 _168_ (
    .A(_007_),
    .B(_039_),
    .X(_106_)
  );
  sky130_fd_sc_hd__xor2_1 _169_ (
    .A(_010_),
    .B(_042_),
    .X(_107_)
  );
  sky130_fd_sc_hd__xnor2_1 _170_ (
    .A(_018_),
    .B(_050_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor3_1 _171_ (
    .A(_088_),
    .B(_090_),
    .C(_091_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nor3_1 _172_ (
    .A(_089_),
    .B(_092_),
    .C(_093_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a21oi_1 _173_ (
    .A1(_003_),
    .A2(_035_),
    .B1(_094_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__xnor2_1 _174_ (
    .A(_001_),
    .B(_033_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__xnor2_1 _175_ (
    .A(_030_),
    .B(_062_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor4_1 _176_ (
    .A(_081_),
    .B(_082_),
    .C(_112_),
    .D(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand4_1 _177_ (
    .A(_109_),
    .B(_110_),
    .C(_111_),
    .D(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a2111oi_0 _178_ (
    .A1(_012_),
    .A2(_044_),
    .B1(_083_),
    .C1(_085_),
    .D1(_086_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _179_ (
    .A(_102_),
    .B(_104_),
    .C(_105_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__o2111ai_1 _180_ (
    .A1(_015_),
    .A2(_047_),
    .B1(_087_),
    .C1(_070_),
    .D1(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _181_ (
    .A(_021_),
    .B(_053_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a211oi_1 _182_ (
    .A1(_020_),
    .A2(_052_),
    .B1(_108_),
    .C1(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand4_1 _183_ (
    .A(_103_),
    .B(_106_),
    .C(_107_),
    .D(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xnor2_1 _184_ (
    .A(_016_),
    .B(_048_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor3_1 _185_ (
    .A(_095_),
    .B(_096_),
    .C(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a2111oi_0 _186_ (
    .A1(_026_),
    .A2(_058_),
    .B1(_097_),
    .C1(_099_),
    .D1(_100_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o2111ai_1 _187_ (
    .A1(_029_),
    .A2(_061_),
    .B1(_101_),
    .C1(_077_),
    .D1(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor4_1 _188_ (
    .A(_069_),
    .B(_072_),
    .C(_075_),
    .D(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _189_ (
    .A0(_066_),
    .A1(_064_),
    .S(_080_),
    .X(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[0].addk  (
    .a(a[0]),
    .b(b[0]),
    .c_in(c_in),
    .c_out(carry[1]),
    .sum(sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[10].addk  (
    .a(a[10]),
    .b(b[10]),
    .c_in(carry[10]),
    .c_out(carry[11]),
    .sum(sum[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[11].addk  (
    .a(a[11]),
    .b(b[11]),
    .c_in(carry[11]),
    .c_out(carry[12]),
    .sum(sum[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[12].addk  (
    .a(a[12]),
    .b(b[12]),
    .c_in(carry[12]),
    .c_out(carry[13]),
    .sum(sum[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[13].addk  (
    .a(a[13]),
    .b(b[13]),
    .c_in(carry[13]),
    .c_out(carry[14]),
    .sum(sum[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[14].addk  (
    .a(a[14]),
    .b(b[14]),
    .c_in(carry[14]),
    .c_out(carry[15]),
    .sum(sum[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[15].addk  (
    .a(a[15]),
    .b(b[15]),
    .c_in(carry[15]),
    .c_out(carry[16]),
    .sum(sum[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[16].addk  (
    .a(a[16]),
    .b(b[16]),
    .c_in(carry[16]),
    .c_out(carry[17]),
    .sum(sum[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[17].addk  (
    .a(a[17]),
    .b(b[17]),
    .c_in(carry[17]),
    .c_out(carry[18]),
    .sum(sum[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[18].addk  (
    .a(a[18]),
    .b(b[18]),
    .c_in(carry[18]),
    .c_out(carry[19]),
    .sum(sum[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[19].addk  (
    .a(a[19]),
    .b(b[19]),
    .c_in(carry[19]),
    .c_out(carry[20]),
    .sum(sum[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[1].addk  (
    .a(a[1]),
    .b(b[1]),
    .c_in(carry[1]),
    .c_out(carry[2]),
    .sum(sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[20].addk  (
    .a(a[20]),
    .b(b[20]),
    .c_in(carry[20]),
    .c_out(carry[21]),
    .sum(sum[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[21].addk  (
    .a(a[21]),
    .b(b[21]),
    .c_in(carry[21]),
    .c_out(carry[22]),
    .sum(sum[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[22].addk  (
    .a(a[22]),
    .b(b[22]),
    .c_in(carry[22]),
    .c_out(carry[23]),
    .sum(sum[22])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[23].addk  (
    .a(a[23]),
    .b(b[23]),
    .c_in(carry[23]),
    .c_out(carry[24]),
    .sum(sum[23])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[24].addk  (
    .a(a[24]),
    .b(b[24]),
    .c_in(carry[24]),
    .c_out(carry[25]),
    .sum(sum[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[25].addk  (
    .a(a[25]),
    .b(b[25]),
    .c_in(carry[25]),
    .c_out(carry[26]),
    .sum(sum[25])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[26].addk  (
    .a(a[26]),
    .b(b[26]),
    .c_in(carry[26]),
    .c_out(carry[27]),
    .sum(sum[26])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[27].addk  (
    .a(a[27]),
    .b(b[27]),
    .c_in(carry[27]),
    .c_out(carry[28]),
    .sum(sum[27])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[28].addk  (
    .a(a[28]),
    .b(b[28]),
    .c_in(carry[28]),
    .c_out(carry[29]),
    .sum(sum[28])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[29].addk  (
    .a(a[29]),
    .b(b[29]),
    .c_in(carry[29]),
    .c_out(carry[30]),
    .sum(sum[29])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[2].addk  (
    .a(a[2]),
    .b(b[2]),
    .c_in(carry[2]),
    .c_out(carry[3]),
    .sum(sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[30].addk  (
    .a(a[30]),
    .b(b[30]),
    .c_in(carry[30]),
    .c_out(carry[31]),
    .sum(sum[30])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[31].addk  (
    .a(a[31]),
    .b(b[31]),
    .c_in(carry[31]),
    .c_out(carry[32]),
    .sum(sum[31])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[3].addk  (
    .a(a[3]),
    .b(b[3]),
    .c_in(carry[3]),
    .c_out(carry[4]),
    .sum(sum[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[4].addk  (
    .a(a[4]),
    .b(b[4]),
    .c_in(carry[4]),
    .c_out(carry[5]),
    .sum(sum[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[5].addk  (
    .a(a[5]),
    .b(b[5]),
    .c_in(carry[5]),
    .c_out(carry[6]),
    .sum(sum[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[6].addk  (
    .a(a[6]),
    .b(b[6]),
    .c_in(carry[6]),
    .c_out(carry[7]),
    .sum(sum[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[7].addk  (
    .a(a[7]),
    .b(b[7]),
    .c_in(carry[7]),
    .c_out(carry[8]),
    .sum(sum[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[8].addk  (
    .a(a[8]),
    .b(b[8]),
    .c_in(carry[8]),
    .c_out(carry[9]),
    .sum(sum[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:106.12-106.88" *)
  fa \rca_block[9].addk  (
    .a(a[9]),
    .b(b[9]),
    .c_in(carry[9]),
    .c_out(carry[10]),
    .sum(sum[9])
  );
  assign carry[0] = c_in;
  assign _066_ = carry[32];
  assign _064_ = c_in;
  assign c_out = _065_;
  assign _000_ = a[0];
  assign _032_ = b[0];
  assign _011_ = a[1];
  assign _043_ = b[1];
  assign _022_ = a[2];
  assign _054_ = b[2];
  assign _025_ = a[3];
  assign _057_ = b[3];
  assign _026_ = a[4];
  assign _058_ = b[4];
  assign _027_ = a[5];
  assign _059_ = b[5];
  assign _028_ = a[6];
  assign _060_ = b[6];
  assign _029_ = a[7];
  assign _061_ = b[7];
  assign _030_ = a[8];
  assign _062_ = b[8];
  assign _031_ = a[9];
  assign _063_ = b[9];
  assign _001_ = a[10];
  assign _033_ = b[10];
  assign _002_ = a[11];
  assign _034_ = b[11];
  assign _003_ = a[12];
  assign _035_ = b[12];
  assign _004_ = a[13];
  assign _036_ = b[13];
  assign _005_ = a[14];
  assign _037_ = b[14];
  assign _006_ = a[15];
  assign _038_ = b[15];
  assign _007_ = a[16];
  assign _039_ = b[16];
  assign _008_ = a[17];
  assign _040_ = b[17];
  assign _009_ = a[18];
  assign _041_ = b[18];
  assign _010_ = a[19];
  assign _042_ = b[19];
  assign _012_ = a[20];
  assign _044_ = b[20];
  assign _013_ = a[21];
  assign _045_ = b[21];
  assign _014_ = a[22];
  assign _046_ = b[22];
  assign _015_ = a[23];
  assign _047_ = b[23];
  assign _016_ = a[24];
  assign _048_ = b[24];
  assign _017_ = a[25];
  assign _049_ = b[25];
  assign _018_ = a[26];
  assign _050_ = b[26];
  assign _019_ = a[27];
  assign _051_ = b[27];
  assign _020_ = a[28];
  assign _052_ = b[28];
  assign _021_ = a[29];
  assign _053_ = b[29];
  assign _023_ = a[30];
  assign _055_ = b[30];
  assign _024_ = a[31];
  assign _056_ = b[31];
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "cba.sv:3.1-34.10" *)
module cba(a, b, c_in, sum, c_out);
  (* src = "cba.sv:7.29-7.30" *)
  input [63:0] a;
  wire [63:0] a;
  (* src = "cba.sv:8.29-8.30" *)
  input [63:0] b;
  wire [63:0] b;
  (* src = "cba.sv:9.17-9.21" *)
  input c_in;
  wire c_in;
  (* src = "cba.sv:11.18-11.23" *)
  output c_out;
  wire c_out;
  (* src = "cba.sv:14.33-14.38" *)
  wire [2:0] carry;
  (* src = "cba.sv:10.30-10.33" *)
  output [63:0] sum;
  wire [63:0] sum;
  (* src = "cba.sv:24.15-30.14" *)
  \$paramod\cbu\BLOCK_WIDTH=s32'00000000000000000000000000100000  \cbu_block[0].addk  (
    .a(a[31:0]),
    .b(b[31:0]),
    .c_in(c_in),
    .c_out(carry[1]),
    .sum(sum[31:0])
  );
  (* src = "cba.sv:24.15-30.14" *)
  \$paramod\cbu\BLOCK_WIDTH=s32'00000000000000000000000000100000  \cbu_block[1].addk  (
    .a(a[63:32]),
    .b(b[63:32]),
    .c_in(carry[1]),
    .c_out(c_out),
    .sum(sum[63:32])
  );
  assign { carry[2], carry[0] } = { c_out, c_in };
endmodule

(* src = "cba.sv:112.1-122.10" *)
module fa(a, b, c_in, sum, c_out);
  (* src = "cba.sv:113.17-113.18" *)
  wire _00_;
  (* src = "cba.sv:114.17-114.18" *)
  wire _01_;
  (* src = "cba.sv:115.17-115.21" *)
  wire _02_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire _03_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire [1:0] _07_;
  (* src = "cba.sv:120.25-120.30" *)
  wire [1:0] _08_;
  wire [1:0] _09_;
  wire _10_;
  wire [1:0] _11_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:266.22-266.23" *)
  wire _12_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:277.21-277.23" *)
  wire [1:0] _13_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:282.21-282.26" *)
  wire [1:0] _14_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire _15_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [1:0] _16_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:272.12-272.14" *)
  wire _17_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:282.28-282.33" *)
  wire [1:0] _18_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:272.8-272.10" *)
  wire _19_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [1:0] _20_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [1:0] _21_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [1:0] _22_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:215.8-215.10" *)
  wire _23_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:218.21-218.23" *)
  wire [1:0] _24_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [1:0] _25_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.20-214.21" *)
  wire [1:0] _26_;
  wire [1023:0] _27_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.21-222.22" *)
  wire [1:0] _28_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.10-220.11" *)
  wire [31:0] _29_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.13-220.14" *)
  wire [31:0] _30_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.18-222.19" *)
  (* unused_bits = "1" *)
  wire [1:0] _31_;
  wire [1:0] _32_;
  wire [1:0] _33_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:266.22-266.23" *)
  wire _34_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:277.21-277.23" *)
  wire [1:0] _35_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:282.21-282.26" *)
  wire [1:0] _36_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [1:0] _37_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [1:0] _38_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:272.12-272.14" *)
  wire _39_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:282.28-282.33" *)
  wire [1:0] _40_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:272.8-272.10" *)
  wire _41_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [1:0] _42_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [1:0] _43_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [1:0] _44_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:215.8-215.10" *)
  wire _45_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:218.21-218.23" *)
  wire [1:0] _46_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [1:0] _47_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.20-214.21" *)
  wire [1:0] _48_;
  wire [1023:0] _49_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.21-222.22" *)
  wire [1:0] _50_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.10-220.11" *)
  wire [31:0] _51_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.13-220.14" *)
  wire [31:0] _52_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.18-222.19" *)
  (* unused_bits = "1" *)
  wire [1:0] _53_;
  wire [1:0] _54_;
  wire [1:0] _55_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)
  wire [1:0] _56_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  wire [1:0] _57_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:279.26-279.45" *)
  wire [1:0] _58_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)
  wire [1:0] _59_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire [2:0] _60_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:231.18-231.27" *)
  wire _61_;
  (* src = "cba.sv:120.25-120.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _62_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)
  wire [1:0] _63_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  wire [1:0] _64_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:279.26-279.45" *)
  wire [1:0] _65_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)
  wire [1:0] _66_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire [2:0] _67_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:231.18-231.27" *)
  wire _68_;
  (* src = "cba.sv:120.25-120.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _69_;
  (* src = "cba.sv:113.17-113.18" *)
  input a;
  wire a;
  (* src = "cba.sv:114.17-114.18" *)
  input b;
  wire b;
  (* src = "cba.sv:115.17-115.21" *)
  input c_in;
  wire c_in;
  (* src = "cba.sv:117.18-117.23" *)
  output c_out;
  wire c_out;
  (* src = "cba.sv:116.18-116.21" *)
  output sum;
  wire sum;
  sky130_fd_sc_hd__maj3_1 _70_ (
    .A(_02_),
    .B(_00_),
    .C(_01_),
    .X(_04_)
  );
  sky130_fd_sc_hd__xor3_1 _71_ (
    .A(_02_),
    .B(_00_),
    .C(_01_),
    .X(_03_)
  );
  assign _20_ = _33_;
  assign _21_ = _32_;
  assign _22_ = _08_;
  assign _15_ = a;
  assign _12_ = b;
  assign _13_ = _14_;
  assign _16_ = _58_;
  assign _32_ = _59_;
  assign _08_ = _60_[1:0];
  assign _42_ = _55_;
  assign _43_ = _54_;
  assign _44_ = { c_out, sum };
  assign _37_ = _08_;
  assign _34_ = c_in;
  assign _35_ = _36_;
  assign _38_ = _65_;
  assign _54_ = _66_;
  assign { c_out, sum } = _67_[1:0];
  assign _24_ = _33_;
  assign _25_ = _56_;
  assign _26_ = _32_;
  assign _27_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _28_ = _33_;
  assign _31_[0] = _32_[0];
  assign _30_ = 32'd2;
  assign _29_ = 32'd0;
  assign _18_ = { 1'h0, a };
  assign _14_ = { 1'h0, b };
  assign _46_ = _55_;
  assign _47_ = _63_;
  assign _48_ = _54_;
  assign _49_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _50_ = _55_;
  assign _53_[0] = _54_[0];
  assign _52_ = 32'd2;
  assign _51_ = 32'd0;
  assign _40_ = _08_;
  assign _36_ = { 1'h0, c_in };
  assign _02_ = c_in;
  assign _67_[1] = _04_;
  assign _67_[0] = _03_;
  assign _00_ = a;
  assign _01_ = b;
endmodule
