/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "cba.sv:3.1-25.10" *)
module cba(a, b, c_in, sum, c_out);
  (* src = "cba.sv:6.29-6.30" *)
  input [63:0] a;
  wire [63:0] a;
  (* src = "cba.sv:7.29-7.30" *)
  input [63:0] b;
  wire [63:0] b;
  (* src = "cba.sv:8.17-8.21" *)
  input c_in;
  wire c_in;
  (* src = "cba.sv:10.18-10.23" *)
  output c_out;
  wire c_out;
  (* src = "cba.sv:13.23-13.28" *)
  wire [16:0] carry;
  (* src = "cba.sv:9.30-9.33" *)
  output [63:0] sum;
  wire [63:0] sum;
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[0].addk  (
    .a(a[3:0]),
    .b(b[3:0]),
    .c_in(c_in),
    .c_out(carry[1]),
    .sum(sum[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[10].addk  (
    .a(a[43:40]),
    .b(b[43:40]),
    .c_in(carry[10]),
    .c_out(carry[11]),
    .sum(sum[43:40])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[11].addk  (
    .a(a[47:44]),
    .b(b[47:44]),
    .c_in(carry[11]),
    .c_out(carry[12]),
    .sum(sum[47:44])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[12].addk  (
    .a(a[51:48]),
    .b(b[51:48]),
    .c_in(carry[12]),
    .c_out(carry[13]),
    .sum(sum[51:48])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[13].addk  (
    .a(a[55:52]),
    .b(b[55:52]),
    .c_in(carry[13]),
    .c_out(carry[14]),
    .sum(sum[55:52])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[14].addk  (
    .a(a[59:56]),
    .b(b[59:56]),
    .c_in(carry[14]),
    .c_out(carry[15]),
    .sum(sum[59:56])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[15].addk  (
    .a(a[63:60]),
    .b(b[63:60]),
    .c_in(carry[15]),
    .c_out(c_out),
    .sum(sum[63:60])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[1].addk  (
    .a(a[7:4]),
    .b(b[7:4]),
    .c_in(carry[1]),
    .c_out(carry[2]),
    .sum(sum[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[2].addk  (
    .a(a[11:8]),
    .b(b[11:8]),
    .c_in(carry[2]),
    .c_out(carry[3]),
    .sum(sum[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[3].addk  (
    .a(a[15:12]),
    .b(b[15:12]),
    .c_in(carry[3]),
    .c_out(carry[4]),
    .sum(sum[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[4].addk  (
    .a(a[19:16]),
    .b(b[19:16]),
    .c_in(carry[4]),
    .c_out(carry[5]),
    .sum(sum[19:16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[5].addk  (
    .a(a[23:20]),
    .b(b[23:20]),
    .c_in(carry[5]),
    .c_out(carry[6]),
    .sum(sum[23:20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[6].addk  (
    .a(a[27:24]),
    .b(b[27:24]),
    .c_in(carry[6]),
    .c_out(carry[7]),
    .sum(sum[27:24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[7].addk  (
    .a(a[31:28]),
    .b(b[31:28]),
    .c_in(carry[7]),
    .c_out(carry[8]),
    .sum(sum[31:28])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[8].addk  (
    .a(a[35:32]),
    .b(b[35:32]),
    .c_in(carry[8]),
    .c_out(carry[9]),
    .sum(sum[35:32])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:21.13-21.113" *)
  cbu \cbu_block[9].addk  (
    .a(a[39:36]),
    .b(b[39:36]),
    .c_in(carry[9]),
    .c_out(carry[10]),
    .sum(sum[39:36])
  );
  assign { carry[16], carry[0] } = { c_out, c_in };
endmodule

(* dynports =  1  *)
(* src = "cba.sv:27.1-56.10" *)
module cbu(a, b, c_in, sum, c_out);
  (* src = "cba.sv:30.29-30.30" *)
  wire _00_;
  (* src = "cba.sv:30.29-30.30" *)
  wire _01_;
  (* src = "cba.sv:30.29-30.30" *)
  wire _02_;
  (* src = "cba.sv:30.29-30.30" *)
  wire _03_;
  (* src = "cba.sv:31.29-31.30" *)
  wire _04_;
  (* src = "cba.sv:31.29-31.30" *)
  wire _05_;
  (* src = "cba.sv:31.29-31.30" *)
  wire _06_;
  (* src = "cba.sv:31.29-31.30" *)
  wire _07_;
  (* src = "cba.sv:32.17-32.21" *)
  wire _08_;
  (* src = "cba.sv:34.18-34.23" *)
  wire _09_;
  (* src = "cba.sv:44.19-44.24" *)
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "cba.sv:42.23-42.38" *)
  wire _16_;
  (* src = "cba.sv:42.23-42.47" *)
  wire _17_;
  (* src = "cba.sv:30.29-30.30" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "cba.sv:31.29-31.30" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "cba.sv:32.17-32.21" *)
  input c_in;
  wire c_in;
  (* src = "cba.sv:34.18-34.23" *)
  output c_out;
  wire c_out;
  (* src = "cba.sv:44.19-44.24" *)
  wire [4:0] carry;
  (* src = "cba.sv:37.9-37.15" *)
  wire prop_0;
  (* src = "cba.sv:37.17-37.23" *)
  wire prop_1;
  (* src = "cba.sv:37.25-37.31" *)
  wire prop_2;
  (* src = "cba.sv:37.33-37.39" *)
  wire prop_3;
  (* src = "cba.sv:37.41-37.49" *)
  wire prop_cbu;
  (* src = "cba.sv:33.30-33.33" *)
  output [3:0] sum;
  wire [3:0] sum;
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(_01_),
    .B(_05_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(_00_),
    .B(_04_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _20_ (
    .A(_03_),
    .B(_07_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(_02_),
    .B(_06_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor4_1 _22_ (
    .A(_11_),
    .B(_12_),
    .C(_13_),
    .D(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__mux2_1 _23_ (
    .A0(_10_),
    .A1(_08_),
    .S(_15_),
    .X(_09_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:52.12-52.88" *)
  fa \rca_block[0].addk  (
    .a(a[0]),
    .b(b[0]),
    .c_in(c_in),
    .c_out(carry[1]),
    .sum(sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:52.12-52.88" *)
  fa \rca_block[1].addk  (
    .a(a[1]),
    .b(b[1]),
    .c_in(carry[1]),
    .c_out(carry[2]),
    .sum(sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:52.12-52.88" *)
  fa \rca_block[2].addk  (
    .a(a[2]),
    .b(b[2]),
    .c_in(carry[2]),
    .c_out(carry[3]),
    .sum(sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cba.sv:52.12-52.88" *)
  fa \rca_block[3].addk  (
    .a(a[3]),
    .b(b[3]),
    .c_in(carry[3]),
    .c_out(carry[4]),
    .sum(sum[3])
  );
  assign carry[0] = c_in;
  assign _10_ = carry[4];
  assign _08_ = c_in;
  assign c_out = _09_;
  assign _00_ = a[0];
  assign _04_ = b[0];
  assign _01_ = a[1];
  assign _05_ = b[1];
  assign _02_ = a[2];
  assign _06_ = b[2];
  assign _03_ = a[3];
  assign _07_ = b[3];
endmodule

(* src = "cba.sv:58.1-68.10" *)
module fa(a, b, c_in, sum, c_out);
  (* src = "cba.sv:59.17-59.18" *)
  wire _00_;
  (* src = "cba.sv:60.17-60.18" *)
  wire _01_;
  (* src = "cba.sv:61.17-61.21" *)
  wire _02_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire _03_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire _04_;
  wire [1:0] _05_;
  wire _06_;
  wire [1:0] _07_;
  wire _08_;
  wire _09_;
  wire [1:0] _10_;
  (* src = "cba.sv:66.25-66.30" *)
  wire [1:0] _11_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:266.22-266.23" *)
  wire _12_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:277.21-277.23" *)
  wire [1:0] _13_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:282.21-282.26" *)
  wire [1:0] _14_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [1:0] _15_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [1:0] _16_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:272.12-272.14" *)
  wire _17_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:282.28-282.33" *)
  wire [1:0] _18_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:272.8-272.10" *)
  wire _19_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [1:0] _20_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [1:0] _21_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [1:0] _22_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:215.8-215.10" *)
  wire _23_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:218.21-218.23" *)
  wire [1:0] _24_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [1:0] _25_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.20-214.21" *)
  wire [1:0] _26_;
  wire [1023:0] _27_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.21-222.22" *)
  wire [1:0] _28_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.10-220.11" *)
  wire [31:0] _29_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.13-220.14" *)
  wire [31:0] _30_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.18-222.19" *)
  (* unused_bits = "1" *)
  wire [1:0] _31_;
  wire [1:0] _32_;
  wire [1:0] _33_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:266.22-266.23" *)
  wire _34_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:277.21-277.23" *)
  wire [1:0] _35_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:282.21-282.26" *)
  wire [1:0] _36_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire _37_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [1:0] _38_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:272.12-272.14" *)
  wire _39_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:282.28-282.33" *)
  wire [1:0] _40_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:272.8-272.10" *)
  wire _41_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [1:0] _42_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [1:0] _43_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [1:0] _44_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:215.8-215.10" *)
  wire _45_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:218.21-218.23" *)
  wire [1:0] _46_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [1:0] _47_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.20-214.21" *)
  wire [1:0] _48_;
  wire [1023:0] _49_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.21-222.22" *)
  wire [1:0] _50_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.10-220.11" *)
  wire [31:0] _51_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.13-220.14" *)
  wire [31:0] _52_;
  (* force_downto = 32'd1 *)
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.18-222.19" *)
  (* unused_bits = "1" *)
  wire [1:0] _53_;
  wire [1:0] _54_;
  wire [1:0] _55_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)
  wire [1:0] _56_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  wire [1:0] _57_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:279.26-279.45" *)
  wire [1:0] _58_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)
  wire [1:0] _59_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire [2:0] _60_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:231.18-231.27" *)
  wire _61_;
  (* src = "cba.sv:66.25-66.37|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _62_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)
  wire [1:0] _63_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  wire [1:0] _64_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:279.26-279.45" *)
  wire [1:0] _65_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)
  wire [1:0] _66_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire [2:0] _67_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:231.18-231.27" *)
  wire _68_;
  (* src = "cba.sv:66.25-66.30|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _69_;
  (* src = "cba.sv:59.17-59.18" *)
  input a;
  wire a;
  (* src = "cba.sv:60.17-60.18" *)
  input b;
  wire b;
  (* src = "cba.sv:61.17-61.21" *)
  input c_in;
  wire c_in;
  (* src = "cba.sv:63.18-63.23" *)
  output c_out;
  wire c_out;
  (* src = "cba.sv:62.18-62.21" *)
  output sum;
  wire sum;
  sky130_fd_sc_hd__maj3_1 _70_ (
    .A(_02_),
    .B(_00_),
    .C(_01_),
    .X(_04_)
  );
  sky130_fd_sc_hd__xor3_1 _71_ (
    .A(_02_),
    .B(_00_),
    .C(_01_),
    .X(_03_)
  );
  assign _42_ = _55_;
  assign _43_ = _54_;
  assign _44_ = _11_;
  assign _37_ = a;
  assign _34_ = b;
  assign _35_ = _36_;
  assign _38_ = _65_;
  assign _54_ = _66_;
  assign _11_ = _67_[1:0];
  assign _20_ = _33_;
  assign _21_ = _32_;
  assign _22_ = { c_out, sum };
  assign _15_ = _11_;
  assign _12_ = c_in;
  assign _13_ = _14_;
  assign _16_ = _58_;
  assign _32_ = _59_;
  assign { c_out, sum } = _60_[1:0];
  assign _46_ = _55_;
  assign _47_ = _63_;
  assign _48_ = _54_;
  assign _49_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _50_ = _55_;
  assign _53_[0] = _54_[0];
  assign _52_ = 32'd2;
  assign _51_ = 32'd0;
  assign _40_ = { 1'h0, a };
  assign _36_ = { 1'h0, b };
  assign _24_ = _33_;
  assign _25_ = _56_;
  assign _26_ = _32_;
  assign _27_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _28_ = _33_;
  assign _31_[0] = _32_[0];
  assign _30_ = 32'd2;
  assign _29_ = 32'd0;
  assign _18_ = _11_;
  assign _14_ = { 1'h0, c_in };
  assign _02_ = c_in;
  assign _60_[1] = _04_;
  assign _60_[0] = _03_;
  assign _00_ = a;
  assign _01_ = b;
endmodule
